/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_Hackontrol */

#ifndef _Included_com_khopan_hackontrol_Hackontrol
#define _Included_com_khopan_hackontrol_Hackontrol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_khopan_hackontrol_Hackontrol
 * Method:    getBotToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_khopan_hackontrol_Hackontrol_getBotToken
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
